"""Sixty clue-based questions for the six Dawn Intel dossiers."""


def question(question_id, prompt, hint, correct, wrong_answers, debrief):
    """Create a question and rotate the correct letter in a predictable way."""
    correct_index = sum(ord(character) for character in question_id) % 4
    options = list(wrong_answers)
    options.insert(correct_index, correct)
    return {
        "id": question_id,
        "prompt": prompt,
        "hints": (hint,),
        "choices": dict(zip("ABCD", options, strict=True)),
        "answer": "ABCD"[correct_index],
        "debrief": debrief,
    }


def dossier(dossier_id, code_name, event, questions):
    """Store an event under a neutral code name so the first clue is a mystery."""
    return {
        "id": dossier_id,
        "code_name": code_name,
        "event": event,
        "questions": questions,
    }


DOSSIERS = (
    dossier(
        "cannae",
        "THE CLOSING WINGS",
        "Battle of Cannae",
        (
            question("cannae-01", "A smaller army lets its center bend backward while strong wings hold. What is it preparing?", "The opposing army is pressing forward in a dense mass.", "A double envelopment", ("A naval blockade", "A siege tower attack", "A mountain ambush"), "At Cannae, Hannibal drew the Romans inward before forces on the flanks enclosed them."),
            question("cannae-02", "A larger infantry force pushes into a narrowing pocket. What danger grows fastest?", "Enemies are appearing on both flanks.", "It loses room to move and use its numbers", ("It gains a safer supply route", "It becomes invisible to scouts", "It can call naval support"), "At Cannae, crowding and attacks from several directions turned Roman numbers into a weakness."),
            question("cannae-03", "You are outnumbered on open ground but have stronger cavalry. Which area should you threaten?", "Cavalry can move around a formation more easily than infantry.", "The enemy's flanks", ("Only its rear supply depot", "A distant mountain pass", "Its center before it moves"), "Hannibal used cavalry success on the flanks to help complete the encirclement."),
            question("cannae-04", "A commander captures a grain depot that feeds an enemy army. What advantage does this give?", "Armies need food and routes to move it.", "It pressures the enemy while improving the commander's position", ("It guarantees every battle will be easy", "It removes the need for scouts", "It changes the weather"), "Taking Cannae placed Hannibal near an important Roman supply source and helped force a decision."),
            question("cannae-05", "A briefing names Rome, Carthage, and Hannibal. Which wider conflict is being investigated?", "Cannae was fought in 216 BCE.", "The Second Punic War", ("The Peloponnesian War", "The Hundred Years' War", "The Crimean War"), "Cannae was a major battle of the Second Punic War between Rome and Carthage."),
            question("cannae-06", "Enemies are closing in from both sides. What is an army's most urgent tactical problem?", "The final gap may soon close behind it.", "Keeping or creating room to maneuver and escape", ("Building a harbor", "Finding a longer plan name", "Waiting for winter"), "Once an encirclement tightens, loss of space and routes can become more dangerous than raw numbers."),
            question("cannae-07", "Why did open terrain suit a commander using fast cavalry on both wings?", "Cavalry needs space to move around an opponent.", "It gave mobile troops room to turn and strike flanks", ("It prevented every infantry attack", "It made supplies unnecessary", "It hid ships from view"), "Open ground gave Hannibal's cavalry room to outmaneuver Rome's mounted forces."),
            question("cannae-08", "An opponent relies on a powerful central push. Which response turns that strength into a risk?", "A deep advance can outrun protection on its sides.", "Draw the center forward, then attack its exposed sides", ("Retreat every unit", "Attack only from the sea", "Ignore the movement"), "Cannae is remembered because the Roman central advance exposed the army to coordinated flank attacks."),
            question("cannae-09", "Which description best defines a double envelopment?", "The attack does not come from just one direction.", "Forces close around both sides of an opponent", ("A fort is surrounded for months", "A fleet sails in two oceans", "Two armies agree to retreat"), "A double envelopment traps an enemy by attacking and closing around both flanks."),
            question("cannae-10", "What is the strongest lesson from Cannae?", "The victory depended on positioning, timing, and coordination.", "Terrain and maneuver can change how useful numbers are", ("The largest army always loses", "Cavalry works only in ancient wars", "Supplies never matter"), "Cannae shows how formation, flank security, mobility, and timing can overcome a numerical disadvantage."),
        ),
    ),
    dossier(
        "agincourt",
        "MUD AND LONGBOWS",
        "Battle of Agincourt",
        (
            question("agincourt-01", "Heavy rain turns a field to mud. Armoured attackers must cross it on foot. What is their immediate problem?", "Mud clings to feet, armor, and equipment.", "Movement becomes slow and exhausting", ("Their maps become more accurate", "Their supply lines become shorter", "Their bows gain range"), "At Agincourt, muddy ground made the French advance far more difficult for heavily equipped troops."),
            question("agincourt-02", "A smaller army has long-range archers and a narrow approach between wooded areas. What is its best plan?", "The attackers have more soldiers.", "Make the larger army advance through the restricted ground", ("Meet it in a wide open plain", "Scatter the archers far behind", "Give up the defensive position"), "A confined approach made it harder for the larger French force to deploy fully against the English line."),
            question("agincourt-03", "What was the most useful battlefield role of massed longbows at Agincourt?", "Longbows could threaten attackers before close combat.", "Disrupt and slow the advancing formation", ("Build a bridge across mud", "Carry supplies by sea", "Replace every infantry soldier"), "Longbow fire added pressure and disorder to the French advance before close fighting began."),
            question("agincourt-04", "An army has fewer troops but holds a prepared line. Which assumption should it avoid?", "Agincourt was an English victory despite French numerical superiority.", "Raw numbers alone decide the outcome", ("A defensive position can help", "Scouts are useful", "Weather affects movement"), "Agincourt shows that numbers interact with ground, formation, weapons, and leadership."),
            question("agincourt-05", "A packed formation is forced through deep mud toward a narrow front. Which problem is most likely?", "The French attack at Agincourt became congested.", "Crowding reduces movement and coordination", ("The formation becomes easier to feed", "The army gains more room", "Weather becomes irrelevant"), "Mud and a restricted battlefield made it difficult for the French to use their numbers in an organized way."),
            question("agincourt-06", "Archers expect mounted attackers. Why place pointed wooden stakes in front of their line?", "English archers used stakes as part of their defense at Agincourt.", "To make a direct mounted charge more dangerous", ("To mark a campsite", "To measure rainfall", "To hide a supply ship"), "Stakes helped protect English archers by complicating attacks against their position."),
            question("agincourt-07", "A dossier mentions Henry V of England fighting French forces. Which long conflict provides the setting?", "The date is 1415.", "The Hundred Years' War", ("The Second Punic War", "The Korean War", "The First World War"), "Agincourt was fought during the Hundred Years' War between England and France."),
            question("agincourt-08", "Rain is expected before armoured troops cross a ploughed field. Which plan is most sensible for the defender?", "The muddy field became a major factor at Agincourt.", "Use the ground to force a slow, crowded approach", ("Move to an open beach", "Ignore the ground", "Send all archers away"), "The English position made the rain-soaked ground part of their defensive advantage."),
            question("agincourt-09", "Which clue separates Agincourt from a modern armored battle?", "It took place in 1415.", "Medieval archers and knights", ("Radar stations", "Aircraft carriers", "Amphibious landing craft"), "Agincourt belongs to the medieval Hundred Years' War, long before radar, carriers, or landing craft."),
            question("agincourt-10", "What best explains the English victory at Agincourt?", "The English combined a defensible position, archers, and favorable ground.", "Terrain, weapons, and formation mattered together", ("Longbows made planning unnecessary", "Rain helps every army equally", "The larger army had no choices"), "Agincourt is best understood through the combined effects of position, mud, longbows, and French congestion."),
        ),
    ),
    dossier(
        "russian_campaign",
        "THE LONG RETREAT",
        "French Invasion of Russia",
        (
            question("russia-01", "An army marches farther from its base while the defender avoids a final battle. What danger grows with every mile?", "Food, equipment, and replacements must travel from behind the army.", "Overstretched supply lines", ("Too many ports", "Too much radar coverage", "A shortage of castles"), "The long distances of the Russian campaign made keeping Napoleon's army supplied increasingly difficult."),
            question("russia-02", "An invader captures a famous capital but the defender refuses to negotiate. What should the invader conclude?", "Napoleon occupied Moscow but did not receive the peace he expected.", "Political goals may remain unmet despite capturing the city", ("The campaign is already won", "Supplies no longer matter", "Winter cannot affect the army"), "Napoleon's occupation of Moscow did not force Russia to make peace, leaving his army in a difficult position."),
            question("russia-03", "Which explanation of the 1812 French disaster is most accurate?", "Long distance, supply shortages, resistance, and cold compounded each other.", "Logistics and winter reinforced each other", ("Cold weather alone explains everything", "A single battle settled the campaign", "The army had too many sea ports"), "The retreat became catastrophic through logistics, exhaustion, enemy pressure, and harsh winter conditions."),
            question("russia-04", "A defending army retreats and removes supplies instead of offering a battle. What is it trying to do?", "An invading army depends on food and shelter along its route.", "Make the invader travel farther with fewer resources", ("Build an airfield", "Hide every river", "End the winter"), "By withdrawing and denying resources, the Russians increased the cost of Napoleon's advance."),
            question("russia-05", "Winter is approaching and an army lacks suitable clothing, forage, and equipment. What should it recognize?", "Napoleon's army was poorly prepared for the coming Russian winter.", "The retreat will become harder unless logistics improve", ("Capturing a city solves equipment problems", "Only cavalry is affected", "Weather helps every traveler"), "Inadequate preparation made the approaching winter far more dangerous during the retreat."),
            question("russia-06", "An army retreats over damaged roads while enemy forces keep pressure on it. Which resource becomes especially important?", "A force still needs to move people, food, and equipment.", "Reliable routes and transport", ("A larger parade ground", "A new capital city", "More ceremonial flags"), "Retreating armies depend on roads, transport, and discipline; all were strained in the Russian campaign."),
            question("russia-07", "A planner says, 'We will take the capital, then the enemy must surrender.' What lesson challenges that claim?", "Russia did not negotiate after Napoleon entered Moscow.", "Military occupation does not guarantee political success", ("Cities never matter", "Winter happens only at sea", "Maps are unnecessary"), "The campaign shows why a plan needs more than a single symbolic objective."),
            question("russia-08", "Which clue identifies this dossier rather than Waterloo?", "Waterloo occurred later in Belgium.", "Moscow and the 1812 winter retreat", ("A narrow English Channel", "Radar control rooms", "Aircraft carriers"), "The French invasion of Russia is closely associated with Moscow and the catastrophic winter retreat of 1812."),
            question("russia-09", "Why can a defender benefit from refusing the quick decisive battle an invader wants?", "Russian forces repeatedly withdrew rather than give Napoleon the ending he sought.", "The invader's supply problem can grow", ("The invader instantly disappears", "The defender no longer needs a plan", "The weather becomes controllable"), "Delaying a powerful invader can force it to spend resources and operate farther from support."),
            question("russia-10", "What is the central planning warning of the 1812 campaign?", "Napoleon reached Moscow but could not turn that into a durable victory.", "Plan logistics and political outcomes, not just the advance", ("Never travel in winter", "A capital is never valuable", "Only cavalry decides campaigns"), "The Russian campaign shows how a successful advance can still fail when supply, weather, and political goals are unresolved."),
        ),
    ),
    dossier(
        "battle_of_britain",
        "EYES IN THE SKY",
        "Battle of Britain",
        (
            question("britain-01", "Ground stations detect incoming aircraft. What is the greatest advantage for a smaller defending air force?", "Fighters are limited and cannot patrol everywhere at once.", "Send fighters toward a confirmed threat", ("Make every fighter fly randomly", "Eliminate the need for pilots", "Hide all airfields underground"), "Radar and fighter control let Britain direct scarce fighters where raids were approaching."),
            question("britain-02", "An attacker wants to weaken an island before attempting an invasion. What must it gain first?", "An invasion force is vulnerable if defenders still control the skies.", "Air superiority", ("A longer land border", "A mountain pass", "A river crossing"), "Germany needed to defeat or weaken British air defenses before an invasion could be practical."),
            question("britain-03", "Radar gives information about an approaching raid. What should a control room do next?", "The Dowding System connected detection with fighter control.", "Assess the report and direct the appropriate squadron", ("Keep it secret from pilots", "Send every plane to one place", "Wait until the raid has finished"), "Britain's system combined radar, reports, control rooms, and fighter squadrons."),
            question("britain-04", "Why is a network of observers and control rooms stronger than radar equipment by itself?", "A defense must turn observations into decisions.", "It can interpret and pass information to the right units", ("It makes weather disappear", "It replaces every aircraft", "It removes the need for training"), "The Battle of Britain depended on organization and communication as well as radar technology."),
            question("britain-05", "A commander has only enough fighters for a few intercepts. Which choice uses early warning best?", "Flying without a target wastes fuel and time.", "Concentrate fighters against the detected raid", ("Patrol every coast equally", "Keep every fighter grounded", "Send fighters to a random city"), "Early warning allowed British commanders to concentrate limited resources rather than scatter them."),
            question("britain-06", "A briefing mentions 1940, the RAF, the Luftwaffe, and an aerial campaign over an island. What event is it?", "The fight centered on control of the air over Britain.", "Battle of Britain", ("Battle of Midway", "Incheon Landing", "Battle of Cannae"), "The Battle of Britain was the 1940 air campaign between the RAF and the Luftwaffe."),
            question("britain-07", "Which clue most clearly separates the Battle of Britain from Midway?", "British radar stations were on land.", "Land-based radar and fighter control", ("Aircraft operating at sea", "A need for intelligence", "The year 1942"), "Britain's land-based radar and control network are central clues for this 1940 air-defense battle."),
            question("britain-08", "What does early warning change most directly in an air-defense battle?", "Radar detected aircraft before they reached their targets.", "The defender's reaction time and positioning", ("The number of oceans", "The weight of medieval armor", "The height of a sea wall"), "Warning gave British fighters time to climb, form up, and intercept incoming raids."),
            question("britain-09", "A force has good technology but poor communication between observers and pilots. What weakness remains?", "Detection alone does not place fighters in the right place.", "Information may not become timely action", ("Weather will always improve", "Enemy aircraft become slower", "Supplies are no longer needed"), "The battle shows that information must be processed and communicated to create an advantage."),
            question("britain-10", "What is the best broad lesson of the Battle of Britain for a smaller defending force?", "Britain combined technology, organization, production, and trained people.", "Use information to focus limited resources", ("Technology works without people", "Air battles need no planning", "Only the largest force can defend"), "Britain's defense depended on a coordinated system that made limited fighter resources more effective."),
        ),
    ),
    dossier(
        "midway",
        "THE BROKEN CODE",
        "Battle of Midway",
        (
            question("midway-01", "Analysts learn an enemy's likely target and timetable before an attack. What is the most valuable immediate use?", "At Midway, U.S. intelligence identified the target code-named AF.", "Position forces to intercept while preserving surprise", ("Broadcast the information to the enemy", "Ignore the report", "Send every ship home"), "U.S. commanders used intelligence about Midway to position carrier forces for an ambush."),
            question("midway-02", "A controlled report about a water problem confirms what an enemy code name means. What has been achieved?", "AF was confirmed as Midway.", "A key intelligence estimate about the target", ("A new landing beach", "A weather forecast for Russia", "A medieval alliance"), "Codebreakers and analysts confirmed that AF referred to Midway, giving the U.S. Navy a major advantage."),
            question("midway-03", "Why were aircraft carriers so important at Midway?", "The battle was decided primarily by carrier-based air power.", "They projected air power across the sea", ("They made reconnaissance unnecessary", "They turned sea into land", "They carried medieval archers"), "Midway demonstrated the growing centrality of carrier aviation in naval warfare."),
            question("midway-04", "A commander thinks enemy carriers are far away, but they are already nearby. What failure occurred?", "Japanese commanders did not know U.S. carriers were positioned near Midway.", "Poor reconnaissance and situational awareness", ("Too much cavalry", "A lack of longbows", "A failed river crossing"), "At Midway, the Japanese strike force was surprised by the presence and position of U.S. carriers."),
            question("midway-05", "A force has intelligence but does not want an opponent to know its code is compromised. What must it protect?", "Future intelligence can be lost if the source is revealed.", "The secrecy of its intelligence advantage", ("A public announcement", "A medieval fortification", "A longer supply route"), "An intelligence advantage is most useful when it can be used without alerting the opponent to its source."),
            question("midway-06", "A sea battle is fought mainly by aircraft launched from carriers. Which event fits best?", "The event took place in the Pacific in 1942.", "Battle of Midway", ("Battle of Agincourt", "Battle of Britain", "Battle of Cannae"), "The Battle of Midway was a pivotal Pacific carrier battle in June 1942."),
            question("midway-07", "Why is reconnaissance still essential after codebreakers give a likely target and date?", "Real operations can change and estimates are not perfect.", "It confirms locations and updates the plan", ("It makes radio messages unnecessary", "It stops aircraft from flying", "It changes the tide"), "Intelligence gave U.S. commanders a strong estimate, but scouting and timely reports remained vital."),
            question("midway-08", "Aircraft return to carriers while the ships are refueling and rearming. Why can this be dangerous?", "Aircraft operations require time, space, and coordination.", "Carriers may be vulnerable during a complicated transition", ("Carriers can move instantly onto land", "The enemy no longer needs fuel", "The battle becomes medieval"), "Carrier decks and hangars are especially vulnerable when aircraft are recovering, refueling, or changing weapons."),
            question("midway-09", "Why did intelligence matter so much at Midway?", "The U.S. had useful warning about Midway while Japan lacked the same awareness of U.S. carriers.", "It helped one side prepare an ambush", ("It made weather impossible", "It removed the need for aircraft", "It guaranteed every prediction"), "Information did not remove risk, but it allowed U.S. forces to prepare for the likely Japanese approach."),
            question("midway-10", "What is the main lesson of Midway for an intelligence team?", "Codebreaking, estimation, reconnaissance, and positioning all contributed.", "Turn information into timely positioning", ("Keep every fact separate", "Use only old maps", "Never take a calculated risk"), "Midway illustrates how intelligence becomes powerful when it supports a realistic operational plan."),
        ),
    ),
    dossier(
        "incheon",
        "TIDES OF SURPRISE",
        "Incheon Landing",
        (
            question("incheon-01", "An amphibious landing needs high water for its largest craft, but the harbor has extreme tides. What does the tide control first?", "At Incheon, tides limited the possible landing dates and hours.", "The date and timing of the landing", ("The number of longbows", "Radar use in 1940", "Weather in Moscow"), "At Incheon, the tide sharply limited when a large landing could be attempted."),
            question("incheon-02", "A narrow approach channel can be blocked if one vessel is disabled. What is the key planning risk?", "Flying Fish Channel was narrow and difficult to navigate.", "A single loss could trap the following force", ("The channel becomes wider at low tide", "Supplies no longer matter", "Aircraft can land on the channel"), "The narrow channel to Incheon meant a disabled vessel could endanger the movement of those behind it."),
            question("incheon-03", "An island near the harbor can fire on an approaching landing force. What should planners consider first?", "Wolmi-do had to be neutralized before the main Incheon landing.", "Secure or neutralize the flanking threat", ("Ignore it because it is small", "Move the harbor inland", "Wait for winter"), "Planners treated Wolmi-do as a serious threat before the main landing phases."),
            question("incheon-04", "A commander chooses a difficult landing site behind an opponent's main front. What benefit is sought?", "Incheon was intended to disrupt North Korean forces operating farther south.", "Surprise and pressure on the opponent's rear areas", ("A beach with no risks", "A shorter medieval war", "A new radar network"), "The Incheon landing aimed to create a surprise threat behind North Korean forces and change the campaign's direction."),
            question("incheon-05", "Why can a huge tidal range be more than a navigation inconvenience?", "Landing craft, schedules, and beach access depend on water level.", "It can determine whether forces reach the beach at all", ("It makes maps unnecessary", "It changes the year of the war", "It removes the need for reconnaissance"), "At Incheon, extreme tides affected both the chosen day and the hour of the assault."),
            question("incheon-06", "Landing troops face a seawall at the harbor. Which equipment becomes immediately useful?", "At Red Beach, troops used ladders to scale Incheon's seawalls.", "Ladders", ("Longbows", "Snowshoes", "Radar dishes"), "The seawalls at Incheon were a physical obstacle, and ladders were used during the assault at Red Beach."),
            question("incheon-07", "A briefing describes September 1950, Korea, a risky amphibious assault, and a tidal harbor. Which event is it?", "The operation followed the early crisis of the Korean War.", "Incheon Landing", ("Battle of Britain", "Battle of Cannae", "Battle of Agincourt"), "The Incheon Landing was a September 1950 amphibious operation during the Korean War."),
            question("incheon-08", "Why combine tide tables with navigation and reconnaissance in a landing plan?", "Incheon's channel, currents, tides, and defenses all created constraints.", "Each factor changes whether the approach is feasible", ("A tide table replaces all maps", "Scouts control weather", "Harbors have no obstacles"), "The operation required detailed knowledge of water, channels, defenses, and timing."),
            question("incheon-09", "A site has currents, mudflats, narrow water, and seawalls. Why might a commander still choose it?", "Incheon was chosen for strategic surprise despite serious risks.", "The surprise may outweigh carefully managed risk", ("Every difficult plan is automatically good", "Tides no longer matter", "No support is needed"), "Incheon shows that an unusual objective can offer surprise, but only when its hazards are planned for in detail."),
            question("incheon-10", "What is the strongest planning lesson from the Incheon Landing?", "The operation depended on timing, hydrography, reconnaissance, and coordination.", "Match strategy to tides, terrain, and logistics", ("Surprise makes planning unnecessary", "Harbors are easier than open beaches", "Technology removes all risk"), "Incheon combined strategic surprise with intensive planning for tides, channels, and defenses."),
        ),
    ),
)
